set_title() {
  print -Pn "%~"
}

GEOMETRY_ECHO=""
GEOMETRY_PREFIX=""

GEOMETRY_PROMPT=(geometry_echo geometry_status geometry_path)
GEOMETRY_RPROMPT+=(geometry_exec_time geometry_jobs geometry_git_remote geometry_git_branch geometry_git_status geometry_docker_machine geometry_kube geometry_exitcode)

GEOMETRY_TITLE=(set_title)
GEOMETRY_CMDTITLE=(geometry_cmd g_at set_title)
GEOMETRY_INFO=()

GEOMETRY_STATUS_SYMBOL="⨭"
GEOMETRY_STATUS_SYMBOL_ERROR="⨴"
GEOMETRY_STATUS_COLOR_ERROR="red"
GEOMETRY_STATUS_COLOR="118"
GEOMETRY_STATUS_COLOR_ROOT="magenta"

GEOMETRY_EXITCODE_COLOR="red"

GEOMETRY_EXEC_TIME_PATIENCE=5

GEOMETRY_KUBE_PIN=false
GEOMETRY_KUBE_SEPARATOR=" :: "
GEOMETRY_KUBE_NAMESPACE_COLOR=242
GEOMETRY_KUBE_COLOR=117

GEOMETRY_GIT_COLOR_DIRTY=red
GEOMETRY_GIT_COLOR_CLEAN=118
GEOMETRY_GIT_SYMBOL_DIRTY="⬢"
GEOMETRY_GIT_SYMBOL_CLEAN="⬢"
GEOMETRY_GIT_GREP=rg
GEOMETRY_GIT_SEPARATOR="::"

GEOMETRY_JOBS_SYMBOL="⎋"
GEOMETRY_JOBS_COLOR=blue

GEOMETRY_PATH_TRUNCATE=4
GEOMETRY_PATH_COLOR="117"
GEOMETRY_PATH_SHOW_BASENAME=false
GEOMETRY_PATH_SYMBOL_HOME="%3~"
