#!/bin/sh
#
# fetch - tiny system info for unix by dwarq7

## INFO

# user is already defined
host="$(hostname)"
os='Gentoo Linux'
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(ls -d /var/db/pkg/*/* | wc -l)"
shell="$($SHELL --version)"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='DE:'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='DE:'
		WM="${DESKTOP_SESSION}"
	elif [ -f "${HOME}/.xinitrc" ]; then
		envtype='WM:'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM:'
fi

## DEFINE COLORS

# better don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

# colors config
lc="${reset}${bold}${yellow}"		# labels
nc="${reset}${bold}${yellow}"		# user and hostname
ic="${reset}${bold}${white}"		# info
c0="${reset}${bold}${magenta}"		# first color
c1="${reset}${bold}${magenta}"	    # second color

## OUTPUT 

cat <<EOF

                  ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}     .-----.      								 ${reset}
${c0}   .\`    _  \`.    ${lc}OS:        ${ic}${os}${reset}
${c0}   \`.   (${c1}_)   ${c0}\`.  ${lc}KERNEL:    ${ic}${kernel}${reset}
${c0}     \`${c1}.        /  ${lc}UPTIME:    ${ic}${uptime}${reset}
${c1}    .\`       .\`   ${lc}PACKAGES:  ${ic}${packages}${reset}
${c1}   /       .\`     ${lc}SHELL:     ${ic}${shell}${reset}
${c1}   \____.-\`       ${lc}${envtype}        ${ic}${WM}${reset}

EOF


## colorpanes

# Author: GekkoP
# Source: http://linuxbbq.org/bbs/viewtopic.php?f=4&t=1656#p33189
 
f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
d=$'\e[1m'
t=$'\e[0m'
v=$'\e[7m'
 
 
cat << EOF
 
 $f0████$d▄$t  $f1████$d▄$t  $f2████$d▄$t  $f3████$d▄$t  $f4████$d▄$t  $f5████$d▄$t  $f6████$d▄$t  $f7████$d▄$t  
 $f0████$d█$t  $f1████$d█$t  $f2████$d█$t  $f3████$d█$t  $f4████$d█$t  $f5████$d█$t  $f6████$d█$t  $f7████$d█$t  
 $f0████$d█$t  $f1████$d█$t  $f2████$d█$t  $f3████$d█$t  $f4████$d█$t  $f5████$d█$t  $f6████$d█$t  $f7████$d█$t  
 $d$f0 ▀▀▀▀  $d$f1 ▀▀▀▀   $f2▀▀▀▀   $f3▀▀▀▀   $f4▀▀▀▀   $f5▀▀▀▀   $f6▀▀▀▀   $f7▀▀▀▀$t  
 
EOF

