#!/bin/sh
date=`date "+%Y-%m-%d-%H%M%S"`
SRC=/
DST=/backups/tmp/

rsync -ax \
--delete \
--progress \
--numeric-ids \
--link-dest=../Latest \
-e "ssh -T -c aes128-gcm@openssh.com -o Compression=no -x" \
$SRC <host>:$DST/Processing-$date \
ssh <host> \
"cd $DST \
&& mv Processing-$date $date 
&& rm -f Latest
&& ln -s $date Latest"
