#!/bin/bash

LANG=C
c=`cat $1`
c=${c//\%/%25}
c=${c//&/%26}
c=${c//=/%3d}
c=${c//+/%2b}
c="code=$c"

r=`(echo -ne "POST / HTTP/1.0\r\nHost: paste.org.ru\r\nCookie: name=$PASTE_ORG_RU_NAME\r\nContent-length: ${#c}\r\n\r\n";echo -n "$c") |nc paste.org.ru 80`
r=${r#*href=\"}
echo "http://paste.org.ru${r%%\">*}"
